accounts/urls.py
from django.urls import path

from .views import (
    DashboardView,
    LoginUsernameView,
    ProfileView,
    RegisterView,
    WalletView,
    login_by_email,
    login_by_otp,
    logout_view, AdminDashboardView,
)

app_name = "accounts"
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginUsernameView.as_view(), name="login"),
    path("login/login-by-email/", login_by_email, name="login_by_email"),
    path("login/login-by-otp/", login_by_otp, name="login_by_otp"),
    path("logout/", logout_view, name="logout"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("admin-dashboard/", AdminDashboardView.as_view(), name="admin_dashboard"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("wallet/", WalletView.as_view(), name="wallet"),
]

config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("doctors/", include("doctors.urls")),
    path("accounts/", include("accounts.urls")),
    path("surveys/", include("surveys.urls")),
    path("appointments/", include("appointments.urls")),
]

# In runserver with gunicorn, added the staticfiles_urlpatterns() to the urlpatterns list.
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

doctors/urls.py
from django.urls import path

from .views import DoctorDetailView, DoctorCreateView, DoctorUpdateView, DoctorDeleteView, ScheduleCreateView, ScheduleUpdateView

app_name = "doctors"
urlpatterns = [
    path("details/<int:pk>/", DoctorDetailView.as_view(), name="detail"),
    path("create/", DoctorCreateView.as_view(), name="create"),
    path("delete/<int:pk>/", DoctorDeleteView.as_view(), name="delete"),
    path("update/<int:pk>/", DoctorUpdateView.as_view(), name="update"),
    path("schedule/<int:pk>/", ScheduleCreateView.as_view(), name="schedule-create"),
    path("schedule/<int:pk>/", ScheduleUpdateView.as_view(), name="schedule-update"),
]

home/urls.py
from django.urls import path

from home.views import IndexHomePageView

app_name = "home"
urlpatterns = [
    path("", IndexHomePageView.as_view(), name="index"),
]

templates/partials/messages.html
{% if messages %}
	{% for msg in messages %}
		<p class="alert alert-{{ msg.tags }}">
			{{ msg }}
		</p>
	{% endfor %}
{% endif %}

templates/partials/navbar.html
{%block navbar%}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:index' %}">Doctor Appointments System</a>
	    <button class="navbar-toggler"
	            type="button"
	            data-bs-toggle="collapse"
	            data-bs-target="#navbarScroll"
	            aria-controls="navbarScroll"
	            aria-expanded="false"
	            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
	        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll"
	            style="--bs-scroll-height: 100px">
                <li class="nav-item">
	                <a class="nav-link active"
	                   aria-current="page"
	                   href="{% url 'home:index' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        {%if user.is_staff %}
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:admin_dashboard' %}">Dashboard</a>
                        {%else%}
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:dashboard' %}">Dashboard</a>
                        {%endif%}
                    </li>
                    <li class="nav-item">
                        {%if user.is_staff %}
                        <a class="nav-link active" aria-current="page" href="{% url 'doctors:create' %}">Create Doctor</a>
                        {%else%}
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:profile' %}">Profile</a>
                        {%endif%}
                    </li>
                    <li class="nav-item">
                        {%if not user.is_staff %}
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:wallet' %}">Wallet</a>
                        {%endif%}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:register' %}">Register</a>
                    </li>
                {% endif %}
                <li class="nav-item dropdown">
	                <a class="nav-link dropdown-toggle"
	                   href="#"
	                   id="navbarScrollingDropdown"
	                   role="button"
	                   data-bs-toggle="dropdown"
	                   aria-expanded="false">Specialities</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                        {% for speciality in specialities %}
                            <li>
                                <a class="dropdown-item"
                                   href="{% url 'home:index' %}?speciality={{ speciality.name }}">{{ speciality.name }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
            <form class="d-flex" method="get">
	            <input class="form-control me-2"
                    name= "name"
	                   type="search"
	                   placeholder="Search By Name"
	                   aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
{% endblock navbar %}