appointments/urls.py
from django.urls import path

from .views import (
    AppointmentDetailView,
    BookingAppointmentView,
    CheckoutAppointmentOrderView,
    PaymentAppointmentOrderView,
    PaymentGatewayVerificationView,
    ShowWeeklyDoctorAvailabilityView,
)

app_name = "appointments"
urlpatterns = [
    path("details/<int:pk>/", AppointmentDetailView.as_view(), name="detail"),
    path(
        "weekly/show/<int:doctor_pk>/",
        ShowWeeklyDoctorAvailabilityView.as_view(),
        name="show_weekly_doctor_availability",
    ),
    path("payment/verify/", PaymentGatewayVerificationView.as_view(), name="payment-verify"),
    path(
        "payment/<str:payment_method>/",
        PaymentAppointmentOrderView.as_view(),
        name="payment-order",
    ),
    path(
        "checkout/<int:doctor_pk>/<str:start_date>/",
        CheckoutAppointmentOrderView.as_view(),
        name="checkout-appointment-order",
    ),
    path(
        "bookings/",
        BookingAppointmentView.as_view(),
        name="booking-appointment",
    ),
]

config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("doctors/", include("doctors.urls")),
    path("accounts/", include("accounts.urls")),
    path("surveys/", include("surveys.urls")),
    path("appointments/", include("appointments.urls")),
]

# In runserver with gunicorn, added the staticfiles_urlpatterns() to the urlpatterns list.
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.urls import path

from home.views import IndexHomePageView

app_name = "home"
urlpatterns = [
    path("", IndexHomePageView.as_view(), name="index"),
]

appointments/models.py
from django.db import models
from django.urls import reverse

from accounts.models import Patient
from doctors.models import Doctor
from utils import BaseModelMixin


class Appointment(BaseModelMixin):
    """
    Represents an appointment between a patient and a doctor.

    Attributes:
    doctor (Doctor): The doctor associated with the appointment.
    patient (Patient): The patient associated with the appointment.
    start_date (DateTimeField): The start date and time of the appointment.
    attended (BooleanField): Indicates whether the appointment has been attended.
    """

    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name="appointments")
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name="appointments")
    start_date = models.DateTimeField(null=False, blank=False)
    attended = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("appointments:detail", args=[self.pk])

appointments/views.py
import datetime
import enum

from django.contrib import messages
from django.core.handlers.wsgi import WSGIRequest
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views import View
from django.views.generic import DetailView, TemplateView

from accounts.mixins import LoginPatientRequiredMixin
from appointments.models import Appointment
from appointments.order import Order
from doctors.models import Doctor, Schedule
from utils.zarinpal import send_request, verify


class PaymentMethod(enum.Enum):
    WALLET = "wallet"
    GATEWAY = "gateway"


class ShowWeeklyDoctorAvailabilityView(LoginPatientRequiredMixin, TemplateView):
    template_name = "appointments/show_weekly_doctor_availability.html"

    @staticmethod
    def get_current_week():
        current_date = timezone.now()

        start_date = current_date
        end_date = start_date + timezone.timedelta(days=7)
        return start_date, end_date

    @staticmethod
    def get_available_slots(doctor, start_date, end_date):
        def get_daily_slots(date):
            day_of_week = date.weekday() + 1
            availabilities = Schedule.objects.filter(doctor=doctor, day_of_week=day_of_week)

            available_slots = []
            slot_duration = timezone.timedelta(minutes=20)

            for availability in availabilities:
                start_time = timezone.make_aware(timezone.datetime.combine(date, availability.start_time))
                end_time = timezone.make_aware(timezone.datetime.combine(date, availability.end_time))

                current_time = start_time
                while current_time + slot_duration <= end_time:
                    slot_end = current_time + slot_duration
                    if not Appointment.objects.filter(
                            Q(start_date__gte=current_time) & Q(start_date__lt=slot_end)
                    ).exists():
                        available_slots.append((current_time, True))
                    else:
                        available_slots.append((current_time, False))
                    current_time += slot_duration

            return available_slots

        if start_date >= end_date:
            return []

        # Generate all dates within the range
        delta = end_date - start_date
        all_available_slots = {}

        for i in range(delta.days):
            current_date = start_date + timezone.timedelta(days=i)
            daily_slots = get_daily_slots(current_date)
            all_available_slots[current_date.strftime("%A %d")] = daily_slots

        return all_available_slots

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        doctor = get_object_or_404(Doctor, pk=kwargs.get("doctor_pk"))
        start_date, end_date = self.get_current_week()
        available_slots = self.get_available_slots(doctor, start_date, end_date)
        context["doctor"] = doctor

        # generate table headers from days of week
        context["days_of_week"] = available_slots
        return context


class CheckoutAppointmentOrderView(LoginPatientRequiredMixin, View):
    @staticmethod
    def get(request, doctor_pk, start_date):
        doctor = get_object_or_404(Doctor, pk=doctor_pk)
        start_date = datetime.datetime.fromisoformat(start_date).strftime("%Y-%m-%d %H:%M")
        context = {"doctor": doctor, "start_date": start_date}
        return render(request, "appointments/checkout_appointment_order.html", context)

    @staticmethod
    def post(request: WSGIRequest, doctor_pk, start_date):
        doctor = get_object_or_404(Doctor, pk=doctor_pk)
        payment_method = request.POST.get("payment_method")
        order = Order(request)
        order.add(doctor_pk, start_date, doctor.fee)
        request.session.modified = True
        return redirect("appointments:payment-order", payment_method=payment_method)


class PaymentAppointmentOrderView(LoginPatientRequiredMixin, View):
    @staticmethod
    def get(request: WSGIRequest, payment_method):
        order = Order(request)
        price = order.get_price()
        if payment_method == PaymentMethod.WALLET.value:
            patient = request.user.patient
            if patient.wallet >= price:
                patient.wallet -= price
                patient.save()
                order.set_status(True)
                return redirect("appointments:booking-appointment")
            else:
                order.set_status(False)
                messages.warning(request, "Insufficient wallet balance.")
                return redirect("appointments:booking-appointment")
        else:
            response = send_request(
                request, price, f"Appointment Order", request.user.patient.phone_number, request.user.email
            )
            return redirect(response["url"])


class PaymentGatewayVerificationView(LoginPatientRequiredMixin, View):
    @staticmethod
    def get(request: WSGIRequest, *args, **kwargs):
        order = Order(request)
        authority = request.GET.get("Authority")
        status = request.GET.get("Status")
        if status == "OK":
            response = verify(order.get_price(), authority)
            if response["status"]:
                order.set_status(True)
                return redirect("appointments:booking-appointment")

        order.set_status(False)
        return redirect("appointments:booking-appointment")


class BookingAppointmentView(LoginPatientRequiredMixin, View):
    def get(self, request):
        order = Order(request)
        doctor = get_object_or_404(Doctor, pk=order.get_doctor_pk())
        start_datetime = timezone.datetime.fromisoformat(order.get_start_date())
        patient = self.request.user.patient
        if order.get_status():
            appointment = Appointment.objects.create(
                doctor=doctor,
                patient=patient,
                start_date=start_datetime,
            )
            # send the appointment to patient
            # send_mail(
            #     "Appointment Order Submitted",
            #     f"""
            #                     Hi Dear {request.user.get_full_name()},
            #                     Your appointment order has been submitted successfully.
            #                     Appointment Detail:
            #                     Doctor: Dr. {doctor.first_name} {doctor.last_name}
            #                     Appointment time start: {start_datetime}
            #                     office address: {doctor.address}
            #
            #                     GoodLuck for your from our team
            #                     """,
            #     None,
            #     [request.user.email],
            # )
            order.clear()
            messages.success(request, "Booking submitted successfully.")
            return render(request, "appointments/booking_status.html", {"appointment": appointment})
        else:
            order.clear()
            messages.warning(request, "Failed to book appointment. Please try again.")
            return redirect("appointments:show_weekly_doctor_availability", doctor_pk=doctor.pk)


class AppointmentDetailView(DetailView):
    model = Appointment
    template_name = "appointments/detail.html"

appointments/templates/appointments/booking_status.html
{% extends "base.html" %}

{% block title %}
	Booking Status
{% endblock %}

{% block content %}
	<div>
		<h1>Booking Detail</h1>
		<p>Your appointment has been booked for {{ appointment.doctor }} on {{ appointment.start_date }}</p>
		<p>Your appointment fee is {{ appointment.doctor.fee }}</p>
		<a href="{% url 'home:index' %}">Go back to home page</a>
	</div>
{% endblock %}

appointments/templates/appointments/checkout_appointment_order.html
{% extends "base.html" %}

{% block title %}
	Check out the order
{% endblock %}

{% block content %}
	<h1>Your Appointment Order</h1>

	<table class="table table-bordered">
		<tr>
			<th>Doctor</th>
			<th>Start date</th>
			<th>Fee</th>
		</tr>
		<tr>
			<td>{{ doctor }}</td>
			<td>{{ start_date }}</td>
			<td>{{ doctor.fee }}</td>
		</tr>

	</table>
	<h2>Select payment method</h2>
	<p>Your wallet balance: {{ request.user.patient.wallet }}</p>
	<form action="" method="post">
		{% csrf_token %}
		<div class="form-group">
			<label for="payment_method">Payment Method:</label>
			<select class="form-control" id="payment_method" name="payment_method">
				<option value="wallet">Wallet</option>
				<option value="gateway">Gateway</option>
			</select>
		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	</form>

{% endblock %}

appointments/templates/appointments/detail.html
{% extends "base.html" %}
{% block title %}
	{{ object }}
{% endblock title %}
{% block content %}
<div class="card justify-content-center text-center bg-light">
	<p class="card-header">
		Patient: {{object.patient}}
	</p>	
	<div class="card-body">
		<p>
			Doctor:<br><a href="{{object.doctor.get_absolute_url}}">{{object.doctor}}</a>
		</p>
		{% if object.attended%}
			<p class="text-info"> Attended </p>
		{% else%}
			<p class="text-info"> Not Attended </p>
		{% endif%}
		<p class= "card-footer">
			Booked for:<br>{{object.start_date}}
		</p>
		
	</div>
</div>




{% endblock content %}

appointments/templates/appointments/show_weekly_doctor_availability.html
{% extends "base.html" %}

{% block title %}
	{{ doctor }} Weekly Availability
{% endblock %}

{% block content %}
	<h1>Book an appointment for a Dr. {{ doctor }}</h1>
	{% for day, hours in days_of_week.items %}
		<h2>{{ day }}</h2>
		{% if hours|length > 0 %}
			<table class="table table-bordered">
				<tr>
					<th>Time</th>
					<th>Book Status</th>
				</tr>
				{% for hour in hours %}
					<tr>
						<td>{{ hour.0|time:"H:i" }} </td>
						<td>
							{% if hour.1 %}
								<a href="{% url "appointments:checkout-appointment-order" doctor.pk hour.0 %}"
								   class="btn btn-primary">Book</a>
							{% else %}
								Booked
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</table>
		{% else %}
			<p>Closed</p>
		{% endif %}
	{% endfor %}
{% endblock %}