accounts/urls.py
from django.urls import path

from .views import (
    DashboardView,
    LoginUsernameView,
    ProfileView,
    RegisterView,
    WalletView,
    login_by_email,
    login_by_otp,
    logout_view, AdminDashboardView,
)

app_name = "accounts"
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginUsernameView.as_view(), name="login"),
    path("login/login-by-email/", login_by_email, name="login_by_email"),
    path("login/login-by-otp/", login_by_otp, name="login_by_otp"),
    path("logout/", logout_view, name="logout"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("admin-dashboard/", AdminDashboardView.as_view(), name="admin_dashboard"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("wallet/", WalletView.as_view(), name="wallet"),
]

config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("doctors/", include("doctors.urls")),
    path("accounts/", include("accounts.urls")),
    path("surveys/", include("surveys.urls")),
    path("appointments/", include("appointments.urls")),
]

# In runserver with gunicorn, added the staticfiles_urlpatterns() to the urlpatterns list.
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

doctors/urls.py
from django.urls import path

from .views import DoctorDetailView, DoctorCreateView, DoctorUpdateView, DoctorDeleteView, ScheduleCreateView, ScheduleUpdateView

app_name = "doctors"
urlpatterns = [
    path("details/<int:pk>/", DoctorDetailView.as_view(), name="detail"),
    path("create/", DoctorCreateView.as_view(), name="create"),
    path("delete/<int:pk>/", DoctorDeleteView.as_view(), name="delete"),
    path("update/<int:pk>/", DoctorUpdateView.as_view(), name="update"),
    path("schedule/<int:pk>/", ScheduleCreateView.as_view(), name="schedule-create"),
    path("schedule/<int:pk>/", ScheduleUpdateView.as_view(), name="schedule-update"),
]

home/urls.py
from django.urls import path

from home.views import IndexHomePageView

app_name = "home"
urlpatterns = [
    path("", IndexHomePageView.as_view(), name="index"),
]

accounts/models.py
from django.core.validators import RegexValidator
from django.db import models

from utils import BaseModelMixin


class Patient(BaseModelMixin):
    """
    This class represents a patient in the system.

    Attributes:
    user: The user associated with this patient.
    phone_number: The unique phone number of the patient.
    address: The address of the patient.
    birth_date: The birth date of the patient.
    wallet: The wallet balance of the patient.
    """

    user = models.OneToOneField("auth.User", on_delete=models.CASCADE)
    phone_number = models.CharField(
        max_length=13,
        unique=True,
        validators=[RegexValidator(r"^(09|\+989)\d{9}$", "Invalid Iranian phone number.")],
    )
    address = models.CharField(max_length=255, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    wallet = models.PositiveIntegerField(default=0)

    def __str__(self):
        """
        Returns the full name of the user associated with this patient.

        Returns:
        str: The full name of the user.
        """
        return self.user.get_full_name()


class OtpToken(BaseModelMixin):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, related_name="otps")
    otp_code = models.CharField(max_length=6)
    otp_expires_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.user.get_full_name()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import Permission, User
from django.core.validators import RegexValidator

from .models import Patient


class LoginUsernameForm(AuthenticationForm):
    pass


class LoginEmailForm(forms.Form):
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={"placeholder": "Enter email-address"}))
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password"}),
    )


class OtpForm(forms.Form):
    phone_number = forms.CharField(
        label="Phone number", widget=forms.TextInput(attrs={"placeholder": "Enter phone number"})
    )
    otp_code = forms.CharField(max_length=6, required=False, widget=forms.TextInput(attrs={"placeholder": "Enter OTP"}))


class RegisterForm(UserCreationForm):
    birth_date = forms.DateField(help_text="Required. Format= YYYY-MM-DD")
    phone_number = forms.CharField(
        max_length=13,
        help_text="Required",
        validators=[RegexValidator(r"^(09|\+989)\d{9}$", "Invalid Iranian phone number.")],
    )
    address = forms.CharField()

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + (
            "email",
            "first_name",
            "last_name",
            "phone_number",
            "birth_date",
            "address",
        )

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            user.user_permissions.add(Permission.objects.get(codename="view_patient"))
            user.user_permissions.add(Permission.objects.get(codename="change_patient"))
            patient = Patient(
                user=user,
                phone_number=self.cleaned_data["phone_number"],
                birth_date=self.cleaned_data["birth_date"],
                address=self.cleaned_data["address"],
            )
            patient.save()

        return user


class UpdatePatientForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=13, required=False, widget=forms.widgets.TextInput)
    address = forms.CharField(
        max_length=255,
        required=False,
        widget=forms.widgets.Textarea,
    )
    birth_date = forms.DateField(
        required=False,
        widget=forms.widgets.SelectDateWidget(years=[n for n in range(1960, 2024)]),
    )

    class Meta:
        model = Patient
        fields = [
            "phone_number",
            "address",
            "birth_date",
        ]


class TransactionForm(forms.ModelForm):
    """
    A form for patient to have a transaction
    """

    CHOICES_TRANSACTION = [
        ("W", "WITHRAW"),
        ("D", "DIPOSIT"),
    ]

    transaction_type = forms.ChoiceField(
        choices=CHOICES_TRANSACTION,
        required=True,
    )

    amount = forms.IntegerField(
        required=True,
        help_text="how much (IRR) ?",
        min_value=0,
    )

    class Meta:
        model = Patient
        fields = ["wallet"]
        exclude = ["wallet"]

    def save(self, commit=True):
        # self.full_clean()
        match (self.cleaned_data["transaction_type"]):
            case "W":
                if self.cleaned_data["amount"] <= self.instance.wallet:
                    self.instance.wallet -= self.cleaned_data["amount"]
                    if commit:
                        self.instance.save()
                    return "Withraw Is Done!"
                else:
                    return "Unable to do Transaction, Please try again."

            case "D":
                self.instance.wallet += self.cleaned_data["amount"]
                if commit:
                    self.instance.save()
                return "Deposit Successfull !"

accounts/views.py
import secrets

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils import timezone as tz
from django.views.generic import CreateView, View
from kavenegar import *

from accounts.forms import LoginEmailForm, LoginUsernameForm, OtpForm, RegisterForm, TransactionForm, UpdatePatientForm
from .models import OtpToken, Patient


class RegisterView(CreateView):
    template_name = "accounts/register.html"
    form_class = RegisterForm
    success_url = reverse_lazy("accounts:login")


class LoginUsernameView(LoginView):
    template_name = "accounts/login.html"
    form_class = LoginUsernameForm


def login_by_email(request):
    if request.method == "GET":
        form = LoginEmailForm()
        return render(request, "accounts/login_by_email.html", context={"form": form})

    if request.method == "POST":
        form = LoginEmailForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")
            else:
                return render(
                    request, "accounts/login_by_email.html", {"form": form, "error": "Invalid email or password."}
                )
        else:
            return render(request, "accounts/login_by_email.html", {"form": form})


def send_otp(user, otp_code):
    api = KavenegarAPI("353433357345617434313879623435757278356F3146706D6143396936574D34797369557146376B6E64733D")
    receptor = user.patient.phone_number
    params = {
        "receptor": receptor,
        "template": "reservationSystem",
        "token": otp_code,
        "type": "sms",
    }
    api.verify_lookup(params)


def login_by_otp(request):
    if request.method == "GET":
        form = OtpForm()
        return render(request, "accounts/login_by_otp.html", {"form": form})
    elif request.method == "POST":
        form = OtpForm(request.POST)
        if form.is_valid():
            phone_number = form.cleaned_data.get("phone_number")
            otp_code = form.cleaned_data.get("otp_code")
            user = User.objects.filter(patient__phone_number=phone_number).first()
            if user:
                if otp_code:
                    otp_token = OtpToken.objects.filter(
                        user=user, otp_code=otp_code, otp_expires_at__gte=tz.now()
                    ).first()
                    if otp_token:
                        login(request, user)
                        return redirect("/")
                    else:
                        return render(
                            request, "accounts/login_by_otp.html", {"form": form, "error": "Invalid or expired OTP."}
                        )
                else:
                    otp_code = secrets.token_hex(3)
                    otp_expires_at = tz.now() + tz.timedelta(minutes=5)
                    OtpToken.objects.create(user=user, otp_code=otp_code, otp_expires_at=otp_expires_at)
                    send_otp(user, otp_code)
                    return render(
                        request,
                        "accounts/login_by_otp.html",
                        {"form": form, "message": "OTP sent to your phone number."},
                    )
            else:
                return render(request, "accounts/login_by_otp.html", {"form": form, "error": "phone number not found."})
        else:
            return render(request, "accounts/login_by_otp.html", {"form": form})


def logout_view(request):
    logout(request)
    return redirect("/")


class DashboardView(LoginRequiredMixin, PermissionRequiredMixin, View):
    """
    Dashboard View provides a page for the patient to have access to :
        -profile details
        -wallet details
        -appointment details
    """

    login_url = "login/"
    permission_required=["accounts.view_patient"]
    template_name = "accounts/dashboard.html"

    def get_context_data(self, **kwargs):
        pass

    def get(self, request):

        try:
            patient = get_object_or_404(Patient, user=request.user)
        except Http404:
            return render(request, "404.html", status=404)

        context = {
            "now": tz.now(),
            "patient": patient,
            "appointments": {
                "attended": patient.appointments.filter(attended=True),
                "not_attended": patient.appointments.filter(attended=False),
            },
        }

        return render(request,
                        "accounts/dashboard.html",
                        context=context)


class AdminDashboardView(LoginRequiredMixin, PermissionRequiredMixin, View):
    template_name = "accounts/admin_dashboard.html"
    login_url = "login/"
    permission_required=["is_staff"]

    def get(self,request):
        return render(request ,
                      "accounts/admin_dashboard.html"
                    )


class ProfileView(LoginRequiredMixin, PermissionRequiredMixin, View):
    """
    A View linked to the patient's profile
    """

    login_url = "login/"
    permission_required = "accounts.view_patient"
    template_name = "accounts/profile.html"

    def get(self, request):
        patient = get_object_or_404(Patient, user=request.user)
        patient_form = UpdatePatientForm(
            request.POST,
            instance=patient,
        )
        return render(
            request, "accounts/profile.html", context={"patient_data": patient.__dict__, "patient_form": patient_form}
        )

    def post(self, request):
        patient = get_object_or_404(Patient, user=request.user)
        patient_form = UpdatePatientForm(request.POST, instance=patient)
        if patient_form.is_valid():
            patient_form.save()
            messages.success(request, "Successfully updated patient")
            return render(
                request,
                "accounts/profile.html",
                context={"patient_data": patient.__dict__, "patient_form": patient_form},
                status=200,
            )
        else:
            messages.error(request, "not valid, please try again.")
            return redirect(to="accounts:profile")


class WalletView(LoginRequiredMixin, PermissionRequiredMixin, View):
    """
    A view for transaction. Works with Patient.wallet. Uses a Transaction Form
    Currently, does not provide actual money transfering ability.
    """

    login_url = "login/"
    permission_required = ("accounts.change_patient", "accounts.view_patient")

    def get(self, request):
        patient = get_object_or_404(Patient, user=request.user)
        transaction_form = TransactionForm()
        return render(
            request,
            "accounts/transact.html",
            context={
                "wallet_balance": patient.wallet,
                "transaction_form": transaction_form,
            },
        )

    def post(self, request):
        patient = get_object_or_404(Patient, user=request.user)
        transaction_form = TransactionForm(request.POST, instance=patient)
        if transaction_form.is_valid():
            message = transaction_form.save()
            messages.success(request, message)
        return redirect(to="accounts:wallet")

accounts/templates/accounts/admin_dashboard.html
{% extends 'base.html' %}
{%load static %}
{%block extra_css %}
<link rel="stylesheet" href="{% static "css/dashboard.css" %}">
{%endblock%}
{%block title %} Welcome {{user.username}} {% endblock %}

{% block content %}
<div class= "card flex-row">
<div class="card-group-body p-2 ">
  <a href="{% url "doctors:create" %}" class="btn btn-outline-primary">Create Doctor</a>
</div>
<div class="card-group-body p-2 ">
  <a href="{% url "home:index" %}" class="btn btn-outline-secondary">View Doctors in Homepage</a>
</div>
</div>
{% endblock %}

accounts/templates/accounts/dashboard.html
{% extends "base.html" %}
{%load static %}
{%load patient_appointments_tag%}
{%block extra_css %}
  <link rel="stylesheet" href="{% static "css/dashboard.css" %}">
{%endblock%}
{%block title %} Welcome {{user.username}} {% endblock %}
{% block content%}
    {% block appointments %}
    {% appointments %}
    {% endblock appointments %}
{%endblock content%}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{%block extra_css %}
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
{%endblock%}
{% block title %}
        Login
{% endblock %}
{% block content %}
    <form method="post" class= "form-container">
        {% csrf_token %}
        {{ form.as_p }}
   <button type="submit" value="Login" class="btn">Login</button>
   <a href="{% url 'accounts:login_by_email' %}"><button type="button">Login By Email</button></a>
   <a href="{% url 'accounts:login_by_otp' %}"> <button type="button">Login By One Time Password</button></a>

    Do not have an account? <a href="{% url 'accounts:register' %}">Register here</a>
    </form>
{% endblock %}

accounts/templates/accounts/login_by_email.html
{% extends 'base.html' %}
{% block title %}
        Login By Email
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
   <button type="submit" value="Login">Login</button>
   <a href="{% url 'accounts:login' %}"><button type="button">Login By Username</button></a>
   <a href="{% url 'accounts:login_by_otp' %}"> <button type="button">Login By One Time Password</button></a>

    Do not have an account? <a href="{% url 'accounts:register' %}">Register here</a>

    </form>


{% endblock %}

accounts/templates/accounts/login_by_otp.html
{% extends 'base.html' %}
{% block title %}
        Login By Otp
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
   <button type="submit" value="Login">Login</button>
   <a href="{% url 'accounts:login' %}"><button type="button">Login By Username</button></a>
   <a href="{% url 'accounts:login_by_email' %}"><button type="button">Login By Email</button></a>

    Do not have an account? <a href="{% url 'accounts:register' %}">Register here</a>

    </form>


{% endblock %}

accounts/templates/accounts/patient_appointments.html
{% block appointments %}
<div class="container text-center "style=" max-height:100%;max-width:100%;">
    <div class="row bg-light " >
        <div class="col p-2" >
            <a class="p-2 btn btn-outline-primary" href="{% url "home:index" %} " >Make an appointment?</a>
        </div>
    </div>
    <div class="row bg-light" >
        <div class="col text-center">
            <p class="text-primary">Your Due Appointments :</p>
            <div class="d-flex flex-row overflow-y-scroll"style="flex-wrap:wrap;">
            {% for appointment in not_attended%}
                <div class="card bg-light text-center mx-auto m-2" style="max-width: 18rem;">
                    <p class="card-header"> {{appointment.doctor}} </p>
                    <a  class="btn card-body" href="{{ appointment.get_absolute_url }}">
                        {% now "Y-m-d" as now %} 
                        {% if appointment.start_date|date:"Y-m-d H:M" > now %}
                        <p class="text-info">{{appointment.start_date}} </p>
                        {% else %}
                        <p class="text-danger">You've missed it!<br>{{appointment.start_date}}</p>
                        {%endif %}
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-sm-6 offset-md-auto p-2  text-center" >
            <p class="text-primary">Your History of appointments:</p>
            <div class="d-flex flex-row overflow-y-scroll"style="flex-wrap:wrap;">
            {% for appointment in attended %}  
            <div class = "card bg-light  mx-auto m-2" style="max-width: 18rem;" >
                <p class="card-header"> {{appointment.doctor}} </p>
                <a href="{{ appointment.get_absolute_url }}" class="btn card-body">
                    <p class="text-info">On: {{appointment.start_date}} </p>
                </a>
            </div> 
            {% endfor %}
        </div>
    </div>
</div>
                
        
    
    
        
</div>
{% endblock appointments %}

accounts/templates/accounts/profile.html
{%extends "base.html" %}
{% load static %}
{% block content %}

<div class = "d-flex justify-content-evenly " >
    <div class = "card bg-light m-2">
            <p class="card-header text-dark">Your Profile Details :</p>
        <div class="card-body text-dark">
                <p>Username : {{user.username}}</p>
                <p>first name : {{user.first_name}}</p>
                <p>Last name : {{user.last_name}}</p>
                <p>Phone : {{patient_data.phone_number}}</p>
                <p>Birth Date : {{patient_data.birth_date}}</p>
                <p>Address : {{patient_data.address}}</p>
                <p>Wallet balance : {{patient_data.wallet}}</p>   
        </div>
    </div>
    <div class="card bg-light p-1 m-2">
        <form method="post" class="card-body form-group d-flex flex-column justify-content-center" >{% csrf_token %}
            {{patient_form.as_p}}
            <button class="btn btn-success" type="submit">change</button>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block title %}
        Register
{% endblock %}
{% load static %}
{%block extra_css %}
  <link rel="stylesheet" href="{% static 'css/register.css' %}">
{%endblock%}
{% block content %}
    <form method="post"class= "form-container">
        {% csrf_token %}
        {{ form.as_p }}
   <button type="submit" value="Register" class= "btn">Register</button>

    Already have an account? <a href="{% url 'accounts:login' %}">Login here</a>

    </form>
    <p>Already have an account?</p>
    <a href="{% url 'accounts:login' %}"> Login here</a>

{% endblock %}

accounts/templates/accounts/transact.html
{% extends 'base.html' %}
{% block title %}
        Register
{% endblock %}
{% load static %}

{% block content %}
    <div>
        Your wallet balance : {{wallet_balance}}
    </div>
    <form method="post" class= "form-container">{% csrf_token %}
        {{transaction_form}}
    <button type="submit" value="Transact" class= "btn">Register</button>
    </form>
{% endblock content %}