appointments/urls.py
from django.urls import path

from .views import (
    AppointmentDetailView,
    BookingAppointmentView,
    CheckoutAppointmentOrderView,
    PaymentAppointmentOrderView,
    PaymentGatewayVerificationView,
    ShowWeeklyDoctorAvailabilityView,
)

app_name = "appointments"
urlpatterns = [
    path("details/<int:pk>/", AppointmentDetailView.as_view(), name="detail"),
    path(
        "weekly/show/<int:doctor_pk>/",
        ShowWeeklyDoctorAvailabilityView.as_view(),
        name="show_weekly_doctor_availability",
    ),
    path("payment/verify/", PaymentGatewayVerificationView.as_view(), name="payment-verify"),
    path(
        "payment/<str:payment_method>/",
        PaymentAppointmentOrderView.as_view(),
        name="payment-order",
    ),
    path(
        "checkout/<int:doctor_pk>/<str:start_date>/",
        CheckoutAppointmentOrderView.as_view(),
        name="checkout-appointment-order",
    ),
    path(
        "bookings/",
        BookingAppointmentView.as_view(),
        name="booking-appointment",
    ),
]

config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("doctors/", include("doctors.urls")),
    path("accounts/", include("accounts.urls")),
    path("surveys/", include("surveys.urls")),
    path("appointments/", include("appointments.urls")),
]

# In runserver with gunicorn, added the staticfiles_urlpatterns() to the urlpatterns list.
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

doctors/urls.py
from django.urls import path

from .views import DoctorDetailView, DoctorCreateView, DoctorUpdateView, DoctorDeleteView, ScheduleCreateView, ScheduleUpdateView

app_name = "doctors"
urlpatterns = [
    path("details/<int:pk>/", DoctorDetailView.as_view(), name="detail"),
    path("create/", DoctorCreateView.as_view(), name="create"),
    path("delete/<int:pk>/", DoctorDeleteView.as_view(), name="delete"),
    path("update/<int:pk>/", DoctorUpdateView.as_view(), name="update"),
    path("schedule/<int:pk>/", ScheduleCreateView.as_view(), name="schedule-create"),
    path("schedule/<int:pk>/", ScheduleUpdateView.as_view(), name="schedule-update"),
]

home/urls.py
from django.urls import path

from home.views import IndexHomePageView

app_name = "home"
urlpatterns = [
    path("", IndexHomePageView.as_view(), name="index"),
]

surveys/urls.py
from django.urls import path

from .views import RateCommentCreateView

app_name = "surveys"
urlpatterns = [
    path("<int:doctor_pk>/rate/create/", RateCommentCreateView.as_view(), name="rate-create"),
    path("<int:doctor_pk>/comment/create/", RateCommentCreateView.as_view(), name="comment-create"),
]

doctors/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import Avg
from django.urls import reverse

from utils import BaseModelMixin


class Speciality(BaseModelMixin):
    """
    Model representing a specialty in the medical system.

    Attributes:
    name: The name of the specialty.
    description: A brief description of the specialty.
    """

    name = models.CharField(
        max_length=255,
        unique=True,
        validators=[RegexValidator(r"^[a-zA-Z]+$", "Specialty name must contain only letters.")],
    )
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Speciality"
        verbose_name_plural = "Specialities"

    def __str__(self):
        return self.name


class Doctor(BaseModelMixin):
    """
    Model representing a doctor in the medical system.

    Attributes:
    first_name: The first name of the doctor.
    last_name: The last name of the doctor.
    specialty: The specialty of the doctor.
    phone_number: The phone number of the doctor.
    email: The email address of the doctor.
    address: The address of the doctor.
    fee: The fee of the doctor.
    """

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    speciality = models.ForeignKey(Speciality, on_delete=models.CASCADE, related_name="doctors")
    phone_number = models.CharField(
        max_length=13,
        unique=True,
        validators=[RegexValidator(r"^(09|\+989)\d{9}$", "Invalid Iranian phone number.")],
    )
    email = models.EmailField(max_length=255, unique=True)
    address = models.CharField(max_length=255)
    fee = models.IntegerField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        """
        Returns the absolute URL of the doctor's detail page.

        Parameters:
        self (Doctor): The instance of the Doctor model.

        Returns:
        str: The absolute URL of the doctor's detail page.

        This method uses Django's reverse function to generate the URL for the
        'detail' view of the 'doctors' app, passing the primary key (pk) of the
        doctor as an argument. The generated URL is returned as a string.
        """
        return reverse("doctors:detail", args=[self.pk])

    @property
    def rate(self):
        """
        Returns the average rating of the doctor.

        Returns:
        float: The average rating of the doctor.
        """
        average_rating = self.rates.aggregate(avg=Avg("score"))["avg"]
        return average_rating if average_rating is not None else "N/A"


class Schedule(BaseModelMixin):
    """
    Model representing a doctor's schedule in the medical system.

    Attributes:
    doctor: The Doctor object associated with the schedule.
    day_of_week: The day of the week for the schedule.
    start_time: The start time of the schedule.
    end_time: The end time of the schedule.
    """

    class DayOfWeek(models.IntegerChoices):
        MONDAY = 1
        TUESDAY = 2
        WEDNESDAY = 3
        THURSDAY = 4
        FRIDAY = 5
        SATURDAY = 6
        SUNDAY = 7

    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name="schedules")
    day_of_week = models.IntegerField(choices=DayOfWeek.choices, unique=True)
    start_time = models.TimeField()
    end_time = models.TimeField()

    class Meta:
        ordering = ("day_of_week",)

    def __str__(self):
        return f"{self.doctor.first_name} {self.doctor.last_name} - {self.get_day_of_week_display()}"

doctors/forms.py
from django import forms

from .models import Schedule


class ScheduleForm(forms.ModelForm):

    class Meta:
        model = Schedule
        fields= "__all__"
        exclude = ["doctor"]

    start_time = forms.TimeField( required=True, 
                                 label="The Start Time",
                                 widget=forms.TimeInput(attrs={'type':'time'}),
                                 input_formats=['%H:%M']
                                )
    end_time = forms.TimeField(required=True, label="The End Time",
                                widget=forms.TimeInput(attrs={'type':'time'}),
                                input_formats=['%H:%M']
                                )
    

doctors/views.py
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView

from doctors.models import Doctor, Schedule

from .forms import ScheduleForm


class DoctorDetailView(DetailView):
    model = Doctor
    template_name = "doctors/detail.html"


class DoctorCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Doctor
    template_name = "doctors/create.html"
    permission_required = "is_staff"
    fields = '__all__'

    def get_success_url(self):
        return reverse("doctors:schedule-create", kwargs={'pk' : self.object.pk})


class DoctorUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Doctor
    template_name = "doctors/update.html"
    permission_required = "is_staff"
    fields = '__all__'
    
    def get_success_url(self):
        return reverse("doctors:schedule-update", kwargs={'pk' : self.object.pk})


class DoctorDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Doctor
    template_name = "doctors/delete.html"
    permission_required = "is_staff"
    success_url = reverse_lazy("home:index")


class ScheduleCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Schedule
    template_name = "doctors/schedule.html"
    permission_required = "is_staff"
    form_class = ScheduleForm
    
    def form_valid(self, form):
        doctor = Doctor.objects.get(pk=self.kwargs["pk"])
        form.instance.doctor = doctor
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse("doctors:detail", kwargs={'pk' : self.object.doctor.pk})
    
class ScheduleUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Schedule
    template_name = "doctors/schedule.html"
    permission_required = "is_staff"
    form_class= ScheduleForm

    def form_valid(self, form):
        doctor = Doctor.objects.get(pk=self.kwargs["pk"])
        form.instance.doctor = doctor
        return super().form_valid(form)
    
    def post(self,request):
        form = ScheduleForm(
            request.POST,
            instance = self.kwargs["pk"])

    def get_success_url(self):
        return reverse("doctors:detail", kwargs={'pk' : self.object.doctor.pk})

doctors/templates/doctors/create.html
{% extends "base.html" %}
{% block title %}
	{{ object }}
{% endblock title %}
{% block content %}
<div class="d-flex justify-content-center">
    <form method="post" class="card bg-light p-2 mx-auto text-center"> {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class= "btn btn-outline-success" value="Save">
    </form>
</div>
{%endblock content%}

doctors/templates/doctors/delete.html
{% extends "base.html" %}
{% block title %}
	{{ object }}
{% endblock title %}
{% block content %}
<div class="d-flex justify-content-center">
<form method="post" class="card bg-light p-2 mx-auto text-center">{% csrf_token %}
    <p>Are you sure you want to delete <br> "{{ object }}"?</p>
    {{ form.as_p }}
    <input type="submit" class="btn btn-danger" value="Confirm">
</form>
</div>
{%endblock content%}

doctors/templates/doctors/detail.html
{% extends "base.html" %}
{% block title %}
	{{ object }}
{% endblock title %}
{% block content %}
	<!-- Doctor's info card -->
	<div class="card">
		<div class="card-body">
			<!-- Doctor's info -->
			<h5 class="card-title">{{ object }}</h5>
			<p class="card-text">Speciality: {{ object.speciality }}</p>
			<p class="card-text">Phone Number: {{ object.phone_number }}</p>
			<p class="card-text">Email: {{ object.email }}</p>
			<p class="card-text">Address: {{ object.address }}</p>
			<p class="card-text">Fee: {{ object.fee }}</p>
			<p class="card-text">Rate: {{ object.rate }} ({{ object.rates.count }})</p>
			<div class="mb-3">
				{% if user.is_authenticated %}
					<a href="{% url "surveys:rate-create" doctor.pk %}" class="btn btn-primary">Send Rate</a>
					<a href="{% url "appointments:show_weekly_doctor_availability" doctor.pk %}"
					   class="btn btn-warning">Set Appointment
					</a>
				{% endif %}
			</div>
			<!-- Buttons -->
			{% if user.is_staff and user.is_authenticated %}
				<a href="{% url "doctors:update" doctor.pk %}" class="btn btn-primary">Edit</a>
				<a href="{% url "doctors:delete" doctor.pk %}" class="btn btn-danger">Delete</a>
				<a href="{% url "doctors:schedule-create" doctor.pk %}" class="btn btn-secondary">Create a Schedule</a>

			{% endif %}
			<!-- End Doctor's Info -->
			<!-- Schedule table -->
			<h5 class="card-title pt-4">Schedule</h5>
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Day of week</th>
						<th scope="col">Start Time</th>
						<th scope="col">End Time</th>
						<th scope="col">Edit</th>
					</tr>
				</thead>
				<tbody>
					{% for day in object.schedules.all %}
						<tr>
							<td>{{ day.get_day_of_week_display }}</td>
							<td>{{ day.start_time }}</td>
							<td>{{ day.end_time }}</td>
							{% if user.is_staff %}
								<td><a href="{% url "doctors:schedule-update" day.pk %}">edit</a></td>
							{% endif %}
						</tr>
					{% endfor %}
				</tbody>
			</table>
			<!-- Schedule table end -->
		</div>
	</div>
	<!-- Add Comment Form -->
	{% if user.is_authenticated %}
		<a class="btn btn-primary mt-2" href="{% url "surveys:comment-create" doctor.pk %}">Write Comment</a>
	{% endif %}
	<!-- Add Comment Form End -->

	<!-- Comments -->
	<h5 class="card-title pt-4">Comments: ({{ object.comments.count }})</h5>
	<div class="card">
		<div class="card-body">
			<!-- Comments list -->
			<ul class="list-group">
				{% for comment in object.comments.all %}
					<li class="list-group-item">
						<p class="mb-1">
							<strong>{{ comment.patient }}</strong> - {{ comment.created_at }}
						</p>
						<p class="card-title">{{ comment.title }}</p>
						<p class="card-text">{{ comment.content }}</p>
					</li>
				{% empty %}
					<p>No comments yet.</p>
				{% endfor %}
			</ul>
		</div>
	</div>
{% endblock content %}

doctors/templates/doctors/schedule.html
{% extends "base.html" %}
{% block title %}
	{{ object }}
{% endblock title %}
{% block content %}
<form method="post"> {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class= "btn" value="Save">
</form>
{%endblock content%}

doctors/templates/doctors/update.html
{% extends "base.html" %}
{% block title %}
	{{ object }}
{% endblock title %}
{% block content %}
<div class="d-flex justify-content-center">
<form method="post" class="card bg-light p-2 mx-auto text-center"> {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class= "btn btn-outline-warning" value="Change">
</form>
</div>
{%endblock content%}